[2025-04-06 00:23:01,440] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: PythonOperator_DAG.Get_Age 2025-04-04T00:00:00+00:00 [queued]>
[2025-04-06 00:23:01,451] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: PythonOperator_DAG.Get_Age 2025-04-04T00:00:00+00:00 [queued]>
[2025-04-06 00:23:01,451] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 00:23:01,451] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2025-04-06 00:23:01,451] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 00:23:01,456] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Get_Age> on 2025-04-04T00:00:00+00:00
[2025-04-06 00:23:01,458] {standard_task_runner.py:54} INFO - Started process 130333 to run task
[2025-04-06 00:23:01,486] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'PythonOperator_DAG', 'Get_Age', '2025-04-04T00:00:00+00:00', '--job_id', '57', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/py_dag.py', '--cfg_path', '/tmp/tmpchch4nzs']
[2025-04-06 00:23:01,487] {standard_task_runner.py:78} INFO - Job 57: Subtask Get_Age
[2025-04-06 00:23:01,515] {logging_mixin.py:120} INFO - Running <TaskInstance: PythonOperator_DAG.Get_Age 2025-04-04T00:00:00+00:00 [running]> on host ROGZephyrusG14GA401QHGA401QH2abf6ae9
[2025-04-06 00:23:01,542] {taskinstance.py:1150} ERROR - init_age() missing 1 required positional argument: 'ti'
Traceback (most recent call last):
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/parveensharma/Documents/PythonPractice/Airflow_ETL/airflow_etl_venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: init_age() missing 1 required positional argument: 'ti'
[2025-04-06 00:23:01,543] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=PythonOperator_DAG, task_id=Get_Age, execution_date=20250404T000000, start_date=20250405T185301, end_date=20250405T185301
[2025-04-06 00:23:06,430] {local_task_job.py:102} INFO - Task exited with return code 1
